on:
  push:
    paths:
      - R/**
      - DESCRIPTION
      - .github/workflows/R-CMD-check.yaml

name: R-CMD-check

jobs:

  R-CMD-check:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@master

      - uses: r-lib/actions/setup-tinytex@master

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache-version: 2
          extra-packages: rcmdcheck, devtools, styler

      - name: Style package
        run: |
          styler::style_pkg()
        shell: Rscript {0}

      - uses: EndBug/add-and-commit@v8
        with:
          default_author: github_actions
          message: "Styler changes"

      - name: Document package
        run: |
          devtools::document(roclets = c('rd', 'collate', 'namespace', 'vignette'))
        shell: Rscript {0}

      - uses: EndBug/add-and-commit@v8
        with:
          default_author: github_actions
          message: "Current document update"

      - uses: r-lib/actions/check-r-package@v2

      - name: Build package website
        run: |
          pkgdown::build_site()
        shell: Rscript {0}

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
